package lib;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
*/

import org.springframework.web.bind.annotation.RestController;

import java.util.Date;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@RestController
public class Library {
    
    @RequestMapping("/")
    public @ResponseBody String index() {
        return "user is tiro" + new Date();
    }

	public boolean someLibraryMethod() {
		// TODO 自動產生的方法 Stub
		return false;
	}
    
}